### ISSUE TITLE
Compatiable issue with latest CLion

### ISSUE THREAD

**Issue by wuxiaoqiang12** [weisJ/auto-dark-mode#10]
The CLion said:
Plugin Error: Plugin "Auto Dark Mode" is incompatible (until build 201.SNAPSHOT < CL-202.6250.12).
Please tell me how can I fix this issue?

**Comment by weisJ** [comment]
Are you using an eap version of CLion?

**Comment by wuxiaoqiang12** [comment]
Oh, yes. It is eap version. I can move to regular version. Thanks!

**Comment by weisJ** [comment]
If you want to use the eap version you could build the plugin locally by changing the version to 202.* in `build.gradle` and install it from disk.
