### ISSUE TITLE
Idea specified Editor theme

### ISSUE THREAD

**Issue by kuznecc** [weisJ/auto-dark-mode#16]
Probably it isn't a bug but the behavior of a plugin is significantly differs from the past releases.
When I first time installed the plugin (MacOs) it worked like a charm. It switched the 'IDE theme' and nothing more.
But after a few last updates, it started to switch 'editor theme' as well. 

Initially, I specify in IDE the 'editor theme' (cmd+`) and this setting worked for every new or old project for the particular 'IDE theme'. 
But now the 'auto-dark-plugin' continuously overrides this setting. You opens a new project after the dark/light theme switching in macOS 'editor theme' drops to default.

Can you provide an ability to plugin to keep the 'Editor theme' without changing while switching between themes?

**Comment by weisJ** [comment]
Hi,
you can set the ide editor themes that are used for each mode in Settings | Other | Auto Dark Mode.
It's currently not possible to opt out of editor theme switching, but it's something I am working on.

**Comment by weisJ** [comment]
Hi @kuznecc . With the latest version (`1.5.0-*`) you'll be able to disable editor theme switching.

**Comment by kuznecc** [comment]
@weisJ , thanks!
I've updated to the latest version of a plugin today and opted out the editor theme switching. 
But, while switching to the light theme it always uses default editor theme and for dark - always my custom editor theme.

I uninstalled the plugin and the problem remained during manual theme switching. 
Probably the problem somewhere in the settings of my IDE.  :(

Thank you for a new checkbox!

**Comment by weisJ** [comment]
You could configure the editor theme through auto dark mode and check editor theme switching, choosing your custom theme for all modes. This should ensure it is always applied.

**Comment by kuznecc** [comment]
Thanks, @weisJ 
I tested this feature one more time (after the last update) and this parameter isn't project-specific more.

**Comment by weisJ** [comment]
The settings never have been project specific. I’m not sure whether project specific settings are worth the additional complexity.
