### ISSUE TITLE
[IDEA 2020.2] Plugin doesn't seem to save preferences

### ISSUE THREAD

**Issue by friedensfurz** [weisJ/auto-dark-mode#18]
Hey,

first of all thank you for your plugin, it is exactly what I was looking for.

However, I'm facing the problem that your Plugin always resets it's settings each start,
which makes it quite unusable at the moment.

I'm using IDEA 2020.2 Ultimate, if that is relevant.
Maybe someone else is facing the same problem?

Regards :)

**Comment by weisJ** [comment]
Thank you for reporting!
I'll need some further information from you.
- Plugin version.
- IntelliJ log. (Please clear the log. Then change the settings and restart).
- If possible the current `autoDarkMode.xml` config file, which contains the settings.

**Comment by weisJ** [comment]
I have released a new version that should fix the issue. @friedensfurz could you confirm the preferences are saved now?

**Comment by scott-rc** [comment]
@weisJ I'm not the original poster, but your update has fixed the issue for me 😄

**Comment by weisJ** [comment]
Thank you for the confirmation @scott-rc.
