### ISSUE TITLE
Some parts of UI are not updated on theme switch

### ISSUE THREAD

**Issue by eugene-stativka** [weisJ/auto-dark-mode#2]
MacOS Catalina. WebStorm 2020.1. v1.1.0-pre2
I noticed that sometimes some parts of UI are not updated to the respective colour theme.
Please see light toolbars when the dark theme is applied
![image](https://user-images.githubusercontent.com/45566415/79424861-1ec71280-7fc1-11ea-8681-21f3cfcd0544.png)

**Comment by weisJ** [comment]
I am using the official API for switching the theme i.e.
````Java
QuickChangeLookAndFeel.switchLafAndUpdateUI(LafManager.getInstance(), targetLaf, true);
````
I'll have to see if there is a more reliable api but please consider reporting this to Jetbrains.

**Comment by bric3** [comment]
@eugene-stativka I see you are using the material theme, it maybe a good idea to see if it's related to this plugin in particular. Or the combination of the theme and intellij.

**Comment by weisJ** [comment]
@bric3 It also occurs when using the Dracula theme. I have had it happen myself but could not reproduce it reliably.

**Comment by weisJ** [comment]
I wonder if this has to do with updating the laf asynchronously. IntelliJ platform itself only ever calls it synchronously i.e.
````Java
QuickChangeLookAndFeel.switchLafAndUpdateUI(LafManager.getInstance(), targetLaf, false);
````
I guess I'll do the same thing.
However it's still worth while to report that changing the laf asynchronously does not work properly.

**Comment by weisJ** [comment]
@eugene-stativka The new [pre-release](https://github.com/weisJ/auto-dark-mode/releases/tag/v1.1.0-pre3) hopefully resolves this problem.
