### ISSUE TITLE
Didn't work on MacOS (tried CLion and Android Studio)

### ISSUE THREAD

**Issue by feresr** [weisJ/auto-dark-mode#24]
Hi I think this is a really useful plugin! 
Unfortunately, I couldn't get it to work on either IDE (Android Studio / CLion) on macOS, is there a tutorial somewhere I'm supposed to follow?

Installed it first on Android studio (during night time) my theme was already dark so I didn't see any changes, the next morning it was still dark (I restarted the IDE).

Installed it later on CLion, during day time, the theme switched to dark (I was expecting to stay on light mode)

The time/timezone on my machine configured properly.

<img width="698" alt="Screen Shot 2020-11-14 at 13 17 39" src="https://user-images.githubusercontent.com/4985932/99151706-c69ddf00-267b-11eb-9a27-619e7ceb01ca.png">

**Comment by weisJ** [comment]
Did you restart CLion after installing the plugin?

**Comment by feresr** [comment]
I just did now, it's daytime where I am and the IDE is still dark 🙁

**Comment by weisJ** [comment]
Is your system in light mode?

**Comment by feresr** [comment]
Dark

**Comment by weisJ** [comment]
If the OS is in dark mode the expected result is that a dark theme.

**Comment by feresr** [comment]
I'll switch to automatic theme at the OS level and try again. 

Maybe worth mentioning this somewhere, I wasn't expecting the plugin to depend on the OS theme

**Comment by weisJ** [comment]
> I'll switch to automatic theme at the OS level and try again. 
> 
> Maybe worth mentioning this somewhere, I wasn't expecting the plugin to depend on the OS theme

Well I guess the description of the plugin should have given that away:
> Automatically change IDEA theme according to OS settings (dark/light/high contrast).

If you want to change the theme independently from the OS based on the current time this plugin isn't what you are searching for. Maybe [a plugin like this](https://plugins.jetbrains.com/plugin/12006-day-and-night)
is more what you are looking for.

**Comment by feresr** [comment]
You are right, my bad, I'll close the issue and remove the review. Thanks for your assistance!
