### ISSUE TITLE
Auto mode not working on macOS Big Sur

### ISSUE THREAD

**Issue by feferka** [weisJ/auto-dark-mode#25]
Even OS has already day theme, it still switches IJ to dar, i.e. if manually moved to light theme, plugin switch it back to dark.

**Comment by weisJ** [comment]
Did you restart IJ after installing the plugin?

**Comment by feferka** [comment]
Indeed, many times. Tried to reinstall as well.


Sincerely
Pavol
________________________________

**Comment by weisJ** [comment]
I haven't yet been able to test the plugin with macOS Big Sur and won't be able to do so for a while as I don't have access to a machine running it. I'll see what I can do, however without access to a Big Sur machine this won't be much. If possible I would highly appreciate if you could help me here.

**Comment by feferka** [comment]
Yesterday I rebooted my mac and looks it helped also to your plugin. It is back working automagically ...
Sorry for false alarm.

Sincerely
Pavol
________________________________

**Comment by weisJ** [comment]
Thank you for the information. I'll still leave the issue up as unreliably on macOS Big Sur may be possible, which needs investigation.

**Comment by VincentJoshuaET** [comment]
I confirm this.

1. Turn on macOS automatic theme change
2. If Android Studio is opened, then its theme will also change.
3. Close Android Studio and shut down Mac.
4. Turn on Mac, theme automatically changes from light to dark or dark to light.
5. Open Android Studio. Theme is still the one before I closed Android Studio from step 2.

Workaround: Change the theme from System Preferences to Light or Dark and Android Studio will change the theme as well.

**Comment by weisJ** [comment]
> I confirm this.
> 
> 
> 
> 1. Turn on macOS automatic theme change
> 
> 2. If Android Studio is opened, then its theme will also change.
> 
> 3. Close Android Studio and shut down Mac.
> 
> 4. Turn on Mac, theme automatically changes from light to dark or dark to light.
> 
> 5. Open Android Studio. Theme is still the one before I closed Android Studio from step 2.
> 
> 
> 
> Workaround: Change the theme from System Preferences to Light or Dark and Android Studio will change the theme as well.

Thank you for the reproduction steps. Because it's working when Auto mode isn't selected I can narrow down the cause of the issue to the following function:

https://github.com/weisJ/auto-dark-mode/blob/371e81c245a7733957ed0c0d00be43adb2d151e9/macos/src/main/objcpp/DarkModeMacOS.mm#L125

Some information that would be good to have is:
- the value of `effectiveAppearance`
- the return value of https://github.com/weisJ/auto-dark-mode/blob/371e81c245a7733957ed0c0d00be43adb2d151e9/macos/src/main/objcpp/DarkModeMacOS.mm#L132
