### ISSUE TITLE
Support for Intellij 2021.2

### ISSUE THREAD

**Issue by 0b11001111** [weisJ/auto-dark-mode#37]
Hey, first of all thanks for this great plugin! As the title states, the plugin is marked as incompatible after upgrading to Intellij 2021.2 (Pycharm, CLion). Not sure if that has technical reasons or just requires an update of the manifest. It would be fantastic to see an update on this as this is the only way I found so far that enables the automatic theme switching behaviour under Gnome.

**Comment by weisJ** [comment]
Thank you for bringing this up. I'm not always up-to date regarding the latest version of the IDEs. The new version takes some time until it is processed but it should be up in a few days.

**Comment by 0b11001111** [comment]
Thanks Jannis for the quick response and update!

**Comment by weisJ** [comment]
The new version is now available
