### ISSUE TITLE
Make IDEA crash on RHEL 8.5

### ISSUE THREAD

**Issue by YoEight** [weisJ/auto-dark-mode#45]
Greetings!

As the title says, the plugin prevents IDEA IDE from starting. Here's the error message I got:

```
/home/yoeight/.local/share/JetBrains/Toolbox/apps/IDEA-U/ch-0/213.5744.223/jbr/bin/java: symbol lookup error: /tmp/nativeutils1248496824722005276886558020021/libauto-dark-mode-linux-gnome.so: undefined symbol: _ZN4Glib11MainContext19push_thread_defaultEv
```

Thanks for your time.

**Comment by weisJ** [comment]
Are you using Gnome?

**Comment by YoEight** [comment]
I am indeed.

On Fedora 35 I don't have that issue while also running Gnome there. Maybe the difference is about their respective version?

on RHEL 8: Gnome 3.32.2
on Fedora 35: Gnome 41.2

Hope it helps!

**Comment by weisJ** [comment]
There might be a difference in the version of glib. Does https://medium.com/@Aenon/glib-symbol-lookup-bug-in-debian-or-ubuntu-def678dab5a6 apply in your case/help you?

**Comment by YoEight** [comment]
Probably, I was trying RHEL 8 to see if I can use it for my working environment. I'm daily-driving Fedora where that problem is nonexistent. I just filled an issue in case someone is using RHEL 8. I don't have RHEL around right now.

**Comment by weisJ** [comment]
Will close this for now. If you ever can reproduce the issue feel free to reopen.
