### ISSUE TITLE
GTK themes list is incomplete

### ISSUE THREAD

**Issue by tsbarnes** [weisJ/auto-dark-mode#46]
The lists of GTK themes for manual selection don't show all my themes. I was looking at the code and noticed it only shows themes that have a gtk-3.x directory matching the current version. It should include any that have a gtk-3.0 directory as well.

**Comment by weisJ** [comment]
Thank you for reporting this.

> It should include any that have a gtk-3.0 directory as well.

This sounds reasonable. Would you be open to contribute a patch for this?

**Comment by tsbarnes** [comment]
Sure! I've never worked on a JetBrains plugin before, but I'm pretty sure I can figure it out 👍🏻

**Comment by weisJ** [comment]
I upload a new version containing the fix. Should be available in a couple days.
