### ISSUE TITLE
Support for 2022.1 version

### ISSUE THREAD

**Issue by oae** [weisJ/auto-dark-mode#52]
I have updated IntelliJ to the 2022.1 version and now it says this plugin is not compatible with it.

![image](https://user-images.githubusercontent.com/1043714/163567344-b43c9785-0463-4d46-87ec-b510e1dfa4a5.png)

**Comment by weisJ** [comment]
There have been build with the new version of IntelliJ causing the release to be delayed. The new version is currently awaiting to be moderated. It will probably be available in the next few days.
