### ISSUE TITLE
[Feature Request] Detect system theme with the new libadwaita baked into GNOME 42

### ISSUE THREAD

**Issue by humblebeee** [weisJ/auto-dark-mode#56]
GNOME seems to be moving away from GTK themes (which the plugin is relying on to work on Linux) with the newly released GNOME bringing `libadwaita` and a new Light/Dark switch inside the Settings, but toggling this switch has no effect on JetBrain IDEs with the plugin!

It seems like, this switch only broadcasts the transition signal to apps adopting the new `libadwaita`, it would be very much appreciated if support for this change is added.

I have attached a screencast demonstrating this, GNOME now considers GTK apps "Legacy" as it seems in the GNOME Tweaks app and GNOME apps ported to `libadwaita`, take the theme preference from the switch in the Settings.

Thank you for all the work and effort!

https://user-images.githubusercontent.com/18480836/167836101-5f7fed6a-4659-4c71-83ce-ac017d7df3ec.mp4

**Comment by l0drex** [comment]
Gnome 42 should support the xdg-color-scheme preference, so this should work once #51 is merged.

**Comment by humblebeee** [comment]
Thank you! Closing this.
