### ISSUE TITLE
UI freeze upon exit

### ISSUE THREAD

**Issue by humblebeee** [weisJ/auto-dark-mode#57]
I have been experiencing UI freezes on closing PyCharm and after a little troubleshooting I noticed they only happen when I enable this plugin!

When plugin is enabled I see this line on my Terminal on closing the IDE (executed by `[install-dir]/bin/pycharm.sh`):
```
2022-06-06 23:07:41,892 [ 160834]   WARN - #c.i.d.PerformanceWatcherImpl - UI was frozen for 137071ms, details saved to /home/myusername/.cache/JetBrains/PyCharm2022.1/log/threadDumps-freeze-20220606-230529-PY-221.5787.24-137sec
```

I have attached the above mentioned file plus `idea.log` down below, if anything else needed, let me know.
[logs.zip](https://github.com/weisJ/auto-dark-mode/files/8846830/logs.zip)

System info:
OS: Linux Fedora 36
DE: GNOME 42 on X11
IDE: PyCharm 2022.1 with the latest version of this plugin

**Comment by humblebeee** [comment]
> Does this happen every time?

Yes, if the plugin is enabled! It happens even after disabling the plugin without a relaunch and it goes away only after relaunching the IDE (after disabling the plugin).

As per your request, I went ahead and removed all of the JetBrains config and cache directories and did a brief testing as the following with logs from after the expriment:

1. Clean installing PyCharm and testing without any plugins:
[clean-run-without-plugin.zip](https://github.com/weisJ/auto-dark-mode/files/8864472/clean-run-without-plugin.zip)

2. Removing and clearing all of the config and cache dirs again and this time went ahead installed only the Auto Dark plugin and lanuched and closed PyCharm a few times (observed the freeze every time, one time amounting to 837 seconds!):
[logs-with-plugin.zip](https://github.com/weisJ/auto-dark-mode/files/8864477/logs-with-plugin.zip)

3. With the above config intact, went ahead and disabled the plugin and relaunched the IDE (problem went away):
[logs-with-plugin-disabled.zip](https://github.com/weisJ/auto-dark-mode/files/8864488/logs-with-plugin-disabled.zip)

**Comment by weisJ** [comment]
I currently don’t find as much time for working on my projects as I’d like to. I’ll try to provide you with a version to test sometime this weekend.

**Comment by humblebeee** [comment]
> I currently don’t find as much time for working on my projects as I’d like to. I’ll try to provide you with a version to test sometime this weekend. Thank you for your patience.

Thank you and sorry for the bothering! Good luck and all! :)

**Comment by weisJ** [comment]
The new version containing the fix should be up within the next two days.
