### ISSUE TITLE
Not compatible with WebStorm 2022.2

### ISSUE THREAD

**Issue by 3dmind** [weisJ/auto-dark-mode#60]
The current version of this plugin at the Marketplace is not compatible with the latest release of WebStorm.

The logs shows the following error:

```
2022-07-30 23:00:53,882 [    181]   WARN - #c.i.i.p.PluginManager - Problems found loading plugins:
  The Auto Dark Mode (id=com.github.weisj.darkmode, path=~/Library/Application Support/JetBrains/Toolbox/apps/WebStorm/ch-0/222.3345.108/WebStorm.app.plugins/auto-dark-mode-plugin, version=1.7.0-2021.1) plugin Plugin 'Auto Dark Mode' (version '1.7.0-2021.1') is not compatible with the current version of the IDE, because it requires build 221.* or older but the current build is WS-222.3345.108
```

WebStorm 2022.2
Build #WS-222.3345.108, built on July 22, 2022
Runtime version: 17.0.3+7-b469.32 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.5

**Comment by weisJ** [comment]
Thank you for the report. I am aware of this issue, but as there is a blocking issue for the next version it might take another day or two for the new release to be made available.

**Comment by weisJ** [comment]
The new version should be up within the next two days.

**Comment by claudechinsta** [comment]
> The new version should be up within the next two days.

Amazing work, love this plugin as always!

**Comment by 3dmind** [comment]
It works again, very cool. Thanks for all your work. :-)
