### ISSUE TITLE
Reduce polling of AppleInterfaceStyle to a lower frequency

### ISSUE THREAD

**Issue by Kovah** [weisJ/auto-dark-mode#7]
As Brice Dutheil already pointed out in the [Youtrack issue](https://youtrack.jetbrains.com/issue/IDEA-203554), the plugin currently polls macOS for the current interface style every 3 seconds.

I would like to ask if it's technically possible to reduce this poll to like 30 or 60 seconds to reduce the load a bit? Not sure if it's really needed to check this every 3 seconds.

**Comment by weisJ** [comment]
I think you are confusing this with another project. In [Dark Mode Sync](https://github.com/gilday/dark-mode-sync-plugin) the interface style is polled every 3 seconds.

What this project is doing is the following:
Through JNI a native listener for the interface style property is created which receives events if the theme has changed. So I'm not really doing any polling but rather letting the OS notify me about any changes. This ensures that the plugin doesn't do anything if no OS settings change. Same applies on Windows.

**Comment by Kovah** [comment]
Oops, sorry for that. Seems I had the wrong repo open.

**Comment by weisJ** [comment]
Don’t worry :)
