### ISSUE TITLE
2023.2 compatibility

### ISSUE THREAD

**Issue by maicol07** [weisJ/auto-dark-mode#70]
Hi,
can you add compatibility with 2023.2 EAP?
Thanks

**Comment by weisJ** [comment]
EAO versions aren’t a high priority for me. Though if you submit a PR I’ll be happy to merge and publish :)

**Comment by maicol07** [comment]
Done!

**Comment by DrGrognon** [comment]
Hello !
First of all thanks for all the work and super plugin :)

Do you have any news on when we can expect support for 2023.2 version of IJ ?
My beautiful dark theme is missing me :smiling_face_with_tear: 

May, i can help on something ?

Kudos for the plugin <3

**Comment by weisJ** [comment]
You will have to be patient until September as I am I am travelling until the end of August. It’s always possible to compile it yourself and install manually #74 should work with a bit of adjustment.

**Comment by maicol07** [comment]
@weisJ actually #75 is more updated (since it's based on the 2023.1/2 branch) and I've uploaded the compiled zip so it can be already used

**Comment by DrGrognon** [comment]
Hi, thanks for kind reply.

I tried the build version but doesn't seems to work with my system. (Ubuntu 22.04 /gnome 42.9/IJ 2023.2)
Nothing crash but the switch just do nothing.

If i can help with some debug info please let me know.
Else, i will wait for final version :sweat_smile: 

Whatever, thanks both for your work on this plugin.

**Comment by maicol07** [comment]
@DrGrognon I'm currently using the gnome \< 42 implementation with gsettings, so I didn't test with xsettings. Can you try to install gsettings (I don't know if there is a way, I'm currently using Ubuntu 22.04 on WSL) and use that?

**Comment by DrGrognon** [comment]
Just for you to know:
- Prior to version 2023.2 i was using the plugin and it worked like a charm (same OS, same Gnome version)
- I tried building myself from your branch #75, same problem than the packaged one
- I tried running the plugin from the runIde task and it was weird, sometimes working but displaying no config menu in UI.
I'm unsure i can have gsetting & xsetting but will try and tell you if it helped ;)

**Comment by weisJ** [comment]
A 2023.2 compatible version has been released. @DrGrognon could you provide the idea log file for during switching the system theme (for all possible implementations from the settings).

**Comment by DrGrognon** [comment]
Dear @weisJ 
(sorry for reply, was in long holidays during all September month ^^)
I updated IDEA and plugin to new published version. Not working OOTB.
I used xdg-desktop settings and worked like a charm :+1: 
So i guess it's all ok for me :)
Thanks a lot for your help and concern and this amazing plugin <3
Saved my eyes !
