### ISSUE TITLE
color-scheme in wayland gnome doesn't seem to work

### ISSUE THREAD

**Issue by txomon** [weisJ/auto-dark-mode#72]
Hello!

I have checked the code in #51 and it doesn't seem like the current gnome implementation is caught by the extension. Just in case, I'm referring to the menu button in the upper corner to switch the theme natively.
![image](https://github.com/weisJ/auto-dark-mode/assets/228250/28e92fd1-75d2-4b01-9351-5b5b0fe9faee)

The current key being monitored is `org.freedesktop.appearance:color-scheme`, however checking with gsettings, the key in gnome-shell 44.1 it seems to be `org.gnome.desktop.interface:color-scheme`, with the value `default` when not in dark mode, and `prefer-dark` when in dark mode.

The version I'm running is `1.8.1-2023.1`.

**Comment by weisJ** [comment]
The PR doesn’t reflect the current implementation. See the `2023.1` branch for the latest revision used in version `1.8.1-2023.1`. It does use the `org.gnome.desktop.interface:color-scheme` key. But probably the `default` and `prefer-dark` versions aren't handled.

**Comment by txomon** [comment]
I'm afraid I'm missing too much knowledge on Java/Kotlin to be able to test out stuff without actual pairing :sweat_smile:. I will try to find time in the next couple of weeks and see if I have some luck. One way to maybe lower the bar for contributions could be an standalone cli that works something like:

```
auto-dark-mode-cli --implementation-type gsettings --guess-light-dark false --change-ide-theme true --ide-theme-light "MyLightTheme" --change-editor-theme true --editor-theme-light "MyEditorLightTheme" --check-high-contrast false```

Making this an standalone java cli would make it much easier for me to iterate when testing out by trial and error, as the current setup I achieved forces me to load a whole IDE in debugging mode etc.

**Comment by weisJ** [comment]
Please try out the new pre-release version of the plugin and see whether it fixes the issue for you:
https://plugins.jetbrains.com/plugin/14076-auto-dark-mode/versions/pre-release/387545

**Comment by txomon** [comment]
It seems like both the new and the old plugin work the same, or rather stop
working the same, and that is when I change the settings. Setting up the
plugin to "Xdg-desktop" and then restarting the IDE will make it work
correctly with both versions.

However, if I change between the different settings, it seems to stop
working altogether.

Cheers, Javier

**Comment by txomon** [comment]
@tonyabbott are you able to test out the situation I shared? Choose the xdg-desktop settings in the old one, click OK, restart the IDE, and see if it works?

Cheers, Javier

**Comment by Lesik** [comment]
Switching to the "xdg-desktop" method works for me on GNOME 43. By the way, I don't think this is a Wayland vs. X11 issue but rather dependent on the GNOME version. In a future version, perhaps this plugin could auto-detect which method to use based on some heuristics like GNOME/GTK version. Keeping the switch in the settings is fine for edge cases, but it would provide for a better OOTB experience.

Thanks for this plugin @weisJ by the way. A ~life~eyesaver.
