### ISSUE TITLE
Incompatible with PyCharm versions newer than build 231.*

### ISSUE THREAD

**Issue by nose-gnome** [weisJ/auto-dark-mode#76]
I noticed that PyCharm stopped syncing with my OS theme.  I looked at my plugins to see that it has this error message
`Incompatible: requires IDE build 231.* or earlier`

I'm running:
```
PyCharm 2023.2 (Professional Edition)
Build #PY-232.8660.197, built on July 26, 2023
```

**Comment by LeeRoyManea** [comment]
Same for Rider
