### ISSUE TITLE
Bug with toolbar duplication

### ISSUE THREAD

**Issue by diskree** [weisJ/auto-dark-mode#82]
Hi, I installed this plugin and notice that sometimes when I run the IDE an extra toolbar appears that shouldn't be there:

![image](https://github.com/weisJ/auto-dark-mode/assets/96978370/f665bdfb-0691-45b2-bdd4-2f7dd3f71da1)

Here is info from "Help > About":

```
IntelliJ IDEA 2023.3.5 (Community Edition)
Build #IC-233.14808.21, built on March 12, 2024
Runtime version: 17.0.10+1-b1087.21 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 6.5.0-26-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 24
Registry:
  ide.experimental.ui=true
Non-Bundled Plugins:
  com.github.weisj.darkmode (1.8.2-2023.3)
  Lombook Plugin (233.14808.21)
  com.intellij.plugin.adernov.powershell (2.5.0)
  com.demonwav.minecraft-dev (2023.3-1.7.3)
  me.jaffe2718.devkit (1.3.2)
Kotlin: 233.14808.21-IJ
Current Desktop: ubuntu:GNOME
```

Plugin settings:

![image](https://github.com/weisJ/auto-dark-mode/assets/96978370/9951ec9e-3bf2-48af-a8a9-91a76b75c094)

I suspect that the problem occurs due to a "New UI" IDEA's feature. Here are it's settings:

![image](https://github.com/weisJ/auto-dark-mode/assets/96978370/71c97535-b6d5-4eea-8ac9-9a5d9a445ecd)

Also, it seems strange to me that the default themes were old: "Intellij Light" and "Intellij Dark". The new IDEA's default themes are "Light" and "Dark" now.

**Comment by weisJ** [comment]
The toolbar is definitely an IntelliJ bug, please report it to them. I am using official APIs to change the theme. The default theme will be adjusted with the next version.
