### ISSUE TITLE
Bug with color scheme custom font getting toggled on

### ISSUE THREAD

**Issue by ollosh** [weisJ/auto-dark-mode#83]
**Version:** 2024.1(PyCharm, PhpStorm, DataGrip..)

**Platform:** Arch Linux 6.8.5-arch1-1

**Settings:**
![image](https://github.com/weisJ/auto-dark-mode/assets/12979324/2d8f1e96-6ac5-4839-abfd-6cde481b1dd6)

**Problem:**
Sometimes it happens that my font gets changed when I change my desktop theme. Usually it's this setting that gets somehow checked 
![image](https://github.com/weisJ/auto-dark-mode/assets/12979324/d5c6f7d9-4832-4c19-9a52-0283131b307d)

I have to just uncheck it and the default font gets used, just wanted to raise awareness since I'm not sure if it's a plugin or a ide thing.

**Comment by weisJ** [comment]
I think this is an IDEA issue. The edit scheme is changed through the official API
https://github.com/weisJ/auto-dark-mode/blob/02dae935968f5e3a25338e214664e4b8bd81ae13/plugin/src/main/java/com/github/weisj/darkmode/AutoDarkMode.kt#L114

I would recommend submitting the issue to JetBrains. They will have more insight.

**Comment by ollosh** [comment]
Gotcha, reported the issue and will close this issue https://youtrack.jetbrains.com/issue/WI-77194/Color-scheme-font-enabled-automatically-whenever-a-schema-changes. 

Thanks for all the work btw, love this plugin :heart:!
