### ISSUE TITLE
When switching between devices, preferred theme settings gets changed

### ISSUE THREAD

**Issue by FilipJakab** [weisJ/auto-dark-mode#87]
When I configure themes for Light/Dark it works correctly. Then moving to another computer // (both have KDE - one on Arch, other is Kubuntu)
Dark mode's theme is set to something else then what I set on previous computer.

Otherwise, the plugin works like a charm, thanks :)

PS: Happens on WebStorm, DataGrip and Rider consistently.

**Comment by FilipJakab** [comment]
This is desired config. Will edit this message with how it gets overwritten once I get to another computer.
![image](https://github.com/weisJ/auto-dark-mode/assets/30082602/154d7857-7d5e-40b4-b001-aa0d82719c25)

**Comment by weisJ** [comment]
Are you using the same version of the plugin on both computers? Could you also provide the stored xml settings file for auto dark mode on both machines: https://intellij-support.jetbrains.com/hc/en-us/articles/206544519-Directories-used-by-the-IDE-to-store-settings-caches-plugins-and-logs

**Comment by FilipJakab** [comment]
Here are the settings before opening JetBrains Rider:
[auto-dark-mode-settings-before.txt](https://github.com/user-attachments/files/15775436/auto-dark-mode-settings-before.txt)

Then I opened Rider and the error was visible. So I closed the Rider to see if the xml file will be changed, but the content remained identical.
After opening the IDE for the second time, it showed config correctly..

## NOTE
However, I managed to get around this by setting enabling only IDE Theme, since it includes setting editor theme as well.

## PS
I found out that the `Settings Sync` did not include this plugin.. So I enabled sync for this plugin as well and when I get home, I will check my PC's settings

I wonder if it conflicts with theme being synced from another device while OS Theme might differ. I will exclude UI Themes from `Settings Sync` to amend this possible conflict.

**Comment by FilipJakab** [comment]
Today, after starting IDE on my home PC, the issue disappeared. Perhaps something from the previous comment caused this. I will try to fiddle with it and let you know, if it happens again...

Thanks for the plugin!

EDIT:
So I am more convinced it was caused with the settings sync, as I forgot to disable the settings sync for `UI Settings` in another IDE (WebStorm) and the the issue persisted.

WebStorm's plugin settings with enabled `UI Settings` in `Settings Sync`:

![image](https://github.com/weisJ/auto-dark-mode/assets/30082602/2bd1d1ae-4c84-4e73-94e3-50e5da035b88)


Also the settings XML still holds correct values (WebStorm not yet closed):
```xml
<application>
  <component name="AutoDarkMode">
    <option name="entries">
      <list>
        <Entry>
          <option name="groupIdentifier" value="advanced_linux_settings:Advanced" />
          <option name="name" value="implType" />
          <option name="value" value="XDG_DESKTOP" />
        </Entry>
        <Entry>
          <option name="groupIdentifier" value="advanced_linux_settings:Advanced" />
          <option name="name" value="overrideGtkDetection" />
          <option name="value" value="false" />
        </Entry>
        <Entry>
          <option name="groupIdentifier" value="advanced_linux_settings_hidden" />
          <option name="name" value="executed" />
          <option name="value" value="true" />
        </Entry>
        <Entry>
          <option name="groupIdentifier" value="general_settings:IDE Theme" />
          <option name="name" value="changeIdeTheme" />
          <option name="value" value="true" />
        </Entry>
        <Entry>
          <option name="groupIdentifier" value="general_settings:IDE Theme:group_0" />
          <option name="name" value="lightTheme" />
          <option name="value" value="ReSharperLight" />
        </Entry>
        <Entry>
          <option name="groupIdentifier" value="general_settings:IDE Theme:group_0" />
          <option name="name" value="darkTheme" />
          <option name="value" value="JetBrainsHighContrastTheme" />
        </Entry>
        <Entry>
          <option name="groupIdentifier" value="general_settings:IDE Theme:group_0" />
          <option name="name" value="highContrastTheme" />
          <option name="value" value="JetBrainsHighContrastTheme" />
        </Entry>
        <Entry>
          <option name="groupIdentifier" value="general_settings:Editor Theme" />
          <option name="name" value="changeEditorTheme" />
          <option name="value" value="false" />
        </Entry>
        <Entry>
          <option name="groupIdentifier" value="general_settings:Editor Theme:group_0" />
          <option name="name" value="lightCodeScheme" />
          <option name="value" value="_@user_ReSharper Light" /> <!-- Here is correct value -->
        </Entry>
        <Entry>
          <option name="groupIdentifier" value="general_settings:Editor Theme:group_0" />
          <option name="name" value="darkCodeScheme" />
          <option name="value" value="_@user_High contrast" /> <!-- Here is correct value -->
        </Entry>
        <Entry>
          <option name="groupIdentifier" value="general_settings:Editor Theme:group_0" />
          <option name="name" value="highContrastCodeScheme" />
          <option name="value" value="_@user_Light" />
        </Entry>
        <Entry>
          <option name="groupIdentifier" value="general_settings:Other" />
          <option name="name" value="checkHighContrast" />
          <option name="value" value="false" />
        </Entry>
        <Entry>
          <option name="groupIdentifier" value="__root__group__" />
          <option name="name" value="__settings__version__" />
          <option name="value" value="1.2" />
        </Entry>
        <Entry>
          <option name="groupIdentifier" value="__root__group__" />
          <option name="name" value="__settings__version__" />
          <option name="value" value="1.2" />
        </Entry>
      </list>
    </option>
  </component>
</application>
```


After saving settings without changing anything, the settings gets stored incorrectly (changed entries):

```xml
<Entry>
  <option name="groupIdentifier" value="general_settings:Editor Theme" />
  <option name="name" value="changeEditorTheme" />
  <option name="value" value="false" />
</Entry>
<Entry>
  <option name="groupIdentifier" value="general_settings:Editor Theme:group_0" />
  <option name="name" value="lightCodeScheme" />
  <option name="value" value="_@user_Light" />
</Entry>
<Entry>
  <option name="groupIdentifier" value="general_settings:Editor Theme:group_0" />
  <option name="name" value="darkCodeScheme" />
  <option name="value" value="_@user_Light" />
</Entry>
<Entry>
  <option name="groupIdentifier" value="general_settings:Editor Theme:group_0" />
  <option name="name" value="highContrastCodeScheme" />
  <option name="value" value="_@user_Light" />
</Entry>
```

**Comment by weisJ** [comment]
I don't know why this was happening exactly but glad to hear that you got it resolved :)
