### ISSUE TITLE
Not compatible with the version of your running IDE (IntelliJ IDEA 2024.2)

### ISSUE THREAD

**Issue by bjornbak** [weisJ/auto-dark-mode#88]
![image](https://github.com/user-attachments/assets/ecc046d1-3ae6-4aa5-9ce6-37697ccb19dd)

IntelliJ IDEA 2024.2 still don't support auto-theme on Linux Mint.

**Comment by weisJ** [comment]
Hi, I'm not actively following IntelliJ releases. I will try to publish a compatible version in the next few days. Thank you for your understanding.

**Comment by weisJ** [comment]
Compatible version should be available now

**Comment by bjornbak** [comment]
It is working!
Thank you for creating and maintaining this plugin!!!
