### ISSUE TITLE
The description says, "Linux (Gtk only)" but I am using it KDE Plasma

### ISSUE THREAD

**Issue by dvaerum** [weisJ/auto-dark-mode#91]
Hey, Thanks for adding support for KDE Plasma, I love it 😁

I can, however, see that the description for the Plugin says that it only works with Gtk, but I think we should update this to let the world know that KDE Plasma is also supported.

https://github.com/weisJ/auto-dark-mode/blob/02dae935968f5e3a25338e214664e4b8bd81ae13/plugin/src/main/resources/META-INF/plugin.xml#L30

**Comment by weisJ** [comment]
Ah yes, this indeed hasn’t been updated in a while 😄 Thank you for pointing it out 👍🏼

**Comment by dvaerum** [comment]
I can make a pull request to update the text, but I am not sure that to write instead? But I have 2 suggestions

1. Linux (Gtk and KDE Plasma)
1. Linux (Gtk and QT)

**Comment by weisJ** [comment]
That would be great. You can try to shorten what is in the README. Both your variants are still not accurate.

**Comment by dvaerum** [comment]
I don't think I understand what I should shorten in the README.

I thought so and that is why I did not make a pull request 😉
> Both your variants are still not accurate.

**Comment by weisJ** [comment]
This part

> Linux support is both limited and experimental. At the moment, Linux desktop environments that have an [XSettings](https://www.freedesktop.org/wiki/Specifications/xsettings-spec/) daemon running are supported. Gtk based desktop environments such as Gnome and Xfce ship with such a daemon out of the box. Users of minimalist window managers (such as i3) can choose to run a daemon shipped with Gnome (gsd-xsettings) or Xfce (xfsettingsd), among many choices.
