### ISSUE TITLE
Missing settings page

### ISSUE THREAD

**Issue by L4stIdi0t** [weisJ/auto-dark-mode#92]
Could you maybe switch from light theme to Light with Light Header? 

with the new header certain fields are light and most is dark, Also none of my other apps keep a dark header when switching to light mode

**Comment by weisJ** [comment]
You can change which theme gets applied in which mode through the settings. Or am I misunderstanding your question?

**Comment by weisJ** [comment]
Then your issue should have been about the missing settings page. What OS/DE version are you using, which version of IntelliJ and which plugin version are you running?

**Comment by weisJ** [comment]
No worries. Glad you got it resolved 👍🏼
