### ISSUE TITLE
Upgrading to IntelliJ 2024.3 broke the plugin again...

### ISSUE THREAD

**Issue by bjornbak** [weisJ/auto-dark-mode#93]
... and Jetbrains still haven't managed to build in theme switching.

Please bump the support again :pray:

**Comment by cardil** [comment]
@mexchip please, open a PR with your changes: https://github.com/mexchip/auto-dark-mode/commit/de61e784cfbe5c1bc8fb11ca75c342bc01531e20

**Comment by weisJ** [comment]
New version is submitted but might take a bit to be approved.
