### ISSUE TITLE
IDE Theme resets to default on gnome but editor theme doesnt

### ISSUE THREAD

**Issue by kxmpxtxnt** [weisJ/auto-dark-mode#94]
![image](https://github.com/user-attachments/assets/43840a81-d9f9-4f09-ad38-479b557ec866)
When using this setup, the Implementation type resets itself to Xdg-Desktop, but im using gnome. And at the IDE Theme the Dark theme resets itself to Dark instead of Monokai Pro.

Im using latest version of gnome, intellij and the plugin.

Thanks ahead!

**Comment by weisJ** [comment]
Can you check the logs whether there is something related to auto dark mode. Also can you provide the settings xml file of auto dark mode?

Possible causes are:
- Something gets wrong during serialization.
- Something is wrong with loading the required native library.
In both cases the xdg-desktop implementation is choses as a fallback. As you have said  that the selected theme also isn't saved for you I suspect some settings aren't properly stored.

**Comment by kxmpxtxnt** [comment]
Hey, thanks for your reply.

So this is a warn i get related to the plugin - https://pastes.dev/qv9QoujdGe

**Comment by weisJ** [comment]
Looks like you are missing the required gtk library (libgtkmm3.0).

**Comment by kxmpxtxnt** [comment]
So atleast in the packetmanager they're installed
![image](https://github.com/user-attachments/assets/e37f0a06-def3-4045-8114-9fc9ecc085bd)

**Comment by kxmpxtxnt** [comment]
Oh, silly me. I didnt restart after I installed the package :D

Thank you for your help <3
